USE finalproject;

CREATE TABLE EMPLOYEE_T (EMPLOYEE_ID INT NOT NULL, EMP_NAME VARCHAR(25), EMP_DOB DATE, ADDRESS VARCHAR(30), CITY_STATE_ZIP VARCHAR(30), JOB_TITLE VARCHAR(25), DEGREE VARCHAR(30), EMPLOYEE_SUPERVISOR_ID INT NOT NULL, CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID) );

CREATE TABLE ROOM_T (ROOM_ID INT NOT NULL, ROOM_NAME VARCHAR(25), PHONE_NUM VARCHAR(15), CONSTRAINT ROOM_PK PRIMARY KEY(ROOM_ID) );

CREATE TABLE ROOM_ISSUE_T (ROOMISS_ID INT NOT NULL, ISSUED_DATE DATE, ROOM_ID INT NOT NULL, EMPLOYEE_ID INT NOT NULL, CONSTRAINT ROOM_ISSUE_PK PRIMARY KEY(ROOMISS_ID), CONSTRAINT ROOM_ISSUE_FK1 FOREIGN KEY(ROOM_ID) REFERENCES ROOM_T(ROOM_ID), CONSTRAINT ROOM_ISSUE_FK2 FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE_T(EMPLOYEE_ID) );

CREATE TABLE DEVELOPER_T (DEV_ID INT NOT NULL, CONSTRAINT DEVELOPER_PK PRIMARY KEY (DEV_ID), CONSTRAINT DEVELOPER_FK1 FOREIGN KEY (DEV_ID) REFERENCES EMPLOYEE_T(EMPLOYEE_ID) );

CREATE TABLE ADMINISTRATIVE_T (AD_ID INT NOT NULL, CONSTRAINT ADMINISTRATIVE_PK PRIMARY KEY (AD_ID), CONSTRAINT ADMINISTRATIVE_FK1 FOREIGN KEY (AD_ID) REFERENCES EMPLOYEE_T(EMPLOYEE_ID) );

CREATE TABLE IT_T (IT_ID INT NOT NULL, CONSTRAINT IT_PK PRIMARY KEY (IT_ID), CONSTRAINT IT_FK1 FOREIGN KEY (IT_ID) REFERENCES EMPLOYEE_T(EMPLOYEE_ID) );

CREATE TABLE PROJECT_T (PROJECT_ID INT NOT NULL, PROJECT_NAME VARCHAR(25), START_DATE DATE, END_DATE DATE NULL, BUDGET FLOAT, CONSTRAINT PROJECT_PK PRIMARY KEY (PROJECT_ID) );

CREATE TABLE WORK_LOG_T (LOG_DATE DATE, HOURS FLOAT, DEV_ID INT NOT NULL, PROJECT_ID INT NOT NULL, CONSTRAINT WORK_LOG_FK1 FOREIGN KEY (DEV_ID) REFERENCES DEVELOPER_T(DEV_ID), CONSTRAINT WORK_LOG_FK2 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT_T(PROJECT_ID) );

CREATE TABLE MANAGE_BY_T (PROJECT_ID INT NOT NULL, AD_ID INT NOT NULL, CONSTRAINT MANAGE_BY_FK1 FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT_T(PROJECT_ID), CONSTRAINT MANAGE_BY_FK2 FOREIGN KEY (AD_ID) REFERENCES ADMINISTRATIVE_T(AD_ID) );

CREATE TABLE ADMIN_TICKET_T (ADTICKET_ID INT NOT NULL, DESCRIPTION VARCHAR(400) NOT NULL, SUBMISSION_DATE DATE, COMPLETION_DATE DATE, AD_ID INT NOT NULL, IT_ID INT NOT NULL, CONSTRAINT ADMIN_TICKET_PK PRIMARY KEY (ADTICKET_ID), CONSTRAINT ADMIN_TICKET_FK1 FOREIGN KEY (AD_ID) REFERENCES ADMINISTRATIVE_T(AD_ID), CONSTRAINT ADMIN_TICKET_FK2 FOREIGN KEY (IT_ID) REFERENCES IT_T(IT_ID) );

CREATE TABLE DEV_TICKET_T (DEVTICKET_ID INT NOT NULL, DESCRIPTION VARCHAR(400) NOT NULL, SUBMISSION_DATE DATE, COMPLETION_DATE DATE, DEV_ID INT NOT NULL, IT_ID INT NOT NULL, CONSTRAINT DEV_TICKET_PK PRIMARY KEY (DEVTICKET_ID), CONSTRAINT DEV_TICKET_FK1 FOREIGN KEY (DEV_ID) REFERENCES DEVELOPER_T(DEV_ID), CONSTRAINT DEV_TICKET_FK2 FOREIGN KEY (IT_ID) REFERENCES IT_T(IT_ID) );

CREATE TABLE VENDOR_T (VENDOR_ID INT NOT NULL, VENDOR_NAME VARCHAR(25), ADDRESS VARCHAR(30), PHONE_NUM VARCHAR(15), CONSTRAINT VENDOR_PK PRIMARY KEY (VENDOR_ID) ); 

CREATE TABLE PART_T (PART_ID INT NOT NULL, PART_NAME VARCHAR(25), CONSTRAINT PART_PK PRIMARY KEY (PART_ID) ); 

CREATE TABLE TRANSACTION_T (TRANS_ID INT NOT NULL, COST_PER_UNIT Decimal(6,2), QUANTITY INT NOT NULL, IT_ID INT NOT NULL, PART_ID INT NOT NULL, VENDOR_ID INT NOT NULL, CONSTRAINT TRANSACTION_PK PRIMARY KEY (TRANS_ID), CONSTRAINT TRANSACTION_FK1 FOREIGN KEY (IT_ID) REFERENCES IT_T(IT_ID), CONSTRAINT TRANSACTION_FK2 FOREIGN KEY (PART_ID) REFERENCES PART_T(PART_ID), CONSTRAINT TRANSACTION_FK3 FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR_T(VENDOR_ID) );

